name = "PlutoProfile"
uuid = "ee419aa8-929d-45cd-acf6-76bd043cd7ba"
authors = ["Guillaume Dalle <22795598+gdalle@users.noreply.github.com> and contributors"]
version = "0.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"

[compat]
AbstractTrees = "v0.3"
FlameGraphs = "v0.2"
Pluto = "0.18"
ProfileCanvas = "0.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
